const indicadores = [
{id: 'AREA', text: "Área do conj., expressa em km2, correspondente a área geogr. e não a área elétr."},
{id: 'AREAT', text: "Área do conjunto em km2"},
{id: 'CM', text: "Encargo de uso do sistema de distribuição aplicado à unidade cons. (mensal)"},
{id: 'CMA', text: "Encargo de uso do sistema de distribuição aplicado à unidade consumidora (anual)"},
{id: 'CMM', text: "Consumo médio mensal, em MWh, média aritmética simples do último ano, excluin-"},
{id: 'CMMT', text: "Consumo médio mensal em MWh"},
{id: 'CMMTCO', text: "Energia cons comercial nos últimos 12 meses (ano móvel) MT e BT"},
{id: 'CMMTIN', text: "Energia cons industrial nos últimos 12 meses (ano móvel)  MT e BT"},
{id: 'CMMTOU', text: "Energia cons outras classes nos últimos 12 meses (ano móvel) MT e BT"},
{id: 'CMMTRE', text: "Energia cons residencial nos últimos 12 meses (ano móvel) MT e BT"},
{id: 'CMMTRU', text: "Energia cons rural nos últimos 12 meses (ano móvel) MT e BT"},
{id: 'CMT', text: "Encargo de uso do sistema de distribuição aplicado à unidade cons. (trimestral)"},
{id: 'CODCLSUC', text: "Código da Classe da Unidade Consumidora"},
{id: 'CODCLSUCA', text: "Código da Classe da Unidade Consumidora"},
{id: 'CODCLSUCT', text: "Código da Classe da Unidade Consumidora"},
{id: 'CODMUNUC', text: "Código do Munícipio do Consumidor"},
{id: 'CODMUNUCA', text: "Código do Munícipio do Consumidor"},
{id: 'CODMUNUCT', text: "Código do Munícipio do Consumidor"},
{id: 'COMPCONF', text: "Compensação de UC atendida fora dos limites previstos de DRP ou DRC"},
{id: 'COMPCONT', text: "Compensação pela violação do DIC, FIC ou DMIC"},
{id: 'COMPCONTA', text: "Compensação pela violação do DIC, FIC ou DMIC"},
{id: 'COMPCONTT', text: "Compensação pela violação do DIC, FIC ou DMIC"},
{id: 'CRAfedMed', text: "Créd. Prazo Viol. de solicitações de aferição dos medidores (art. 137)"},
{id: 'CRAnProj', text: "Créd. Prazo Viol. de informação do resultado da análise do projeto (art. 27-B)"},
{id: 'CRCmsnObra', text: "Créd. Prazo Viol. de Comissionamento das obras. (art. 37)"},
{id: 'CREstProj', text: "Créd. Prazo Viol. por estudos, orçamentos e projetos por obras (art. 32)"},
{id: 'CRInform', text: "Créd. Prazo Viol. de informação da relação dos atendimentos (art. 199)"},
{id: 'CRLigA', text: "Créd. Prazo Viol. por ligação de unidade consumidora do grupo A (art. 31)"},
{id: 'CRLigBRr', text: "Créditos cedidos por ligação de consumidor do grupo B em área rural (art. 31)"},
{id: 'CRLigBUb', text: "Créd. Prazo Viol. por ligação de consumidor do grupo B em área urbana (art. 31)"},
{id: 'CRNvCmsn', text: "Créd. Prazo Viol. de Novo comissionamento quando de reprovação. (art. 37)"},
{id: 'CRObGerais', text: "Créd. Prazo Viol. de Conclusão de obra não abrang. nos inc. I e II do art. 34."},
{id: 'CRObra', text: "Créd. Prazo Viol. por Início das Obras (art. 34)"},
{id: 'CRObraPrim', text: "Créd. Prazo Viol. de Conclusão das obras de até 1 km na rede prim. (art. 34)"},
{id: 'CRObraSec', text: "Créd. Prazo Viol. de Conclusão das obras na rede tensão secundária. (art. 34)"},
{id: 'CRPgtoRsc', text: "Créd. Prazo Viol. de ressarc. por meio do pgto, conserto ou subst. (art. 208)"},
{id: 'CRRclCobr', text: "Créd. Prazo Viol. de reclamação de cobrança ou devol. de diferenças (art. 133)"},
{id: 'CRRclDano', text: "Créd. Prazo Viol. de solução ref. à danos não elétricos reclamados (art. 197)"},
{id: 'CRRclVisTc', text: "Créd. Prazo Viol. de solução de reclamação com visita técnica (art. 197)"},
{id: 'CRReanProj', text: "Créd. Prazo Viol. de reanálise do projeto por falta de informação (art. 27-B)"},
{id: 'CRReligIdv', text: "Créd. Prazo Viol. de religação por suspensão indevida do fornec. (art. 176)"},
{id: 'CRRelNorRr', text: "Créd. Prazo Viol. de religação em área rural (art. 176)"},
{id: 'CRRelNorUb', text: "Créd. Prazo Viol. de religação em área urbana (art. 176)"},
{id: 'CRRelUrgRr', text: "Créd. Prazo Viol. de religação de emergência em área rural (art. 176)"},
{id: 'CRRelUrgUb', text: "Créd. Prazo Viol. de religação de emergência em área urbana (art. 176)"},
{id: 'CRResulRsc', text: "Créd. Prazo Viol. de resultado da solicitação de ressarcimento (art. 207)"},
{id: 'CRSubstMed', text: "Créditos cedidos por substituição do medidor com defeito (art. 115)"},
{id: 'CRVistRr', text: "Créd. Prazo Viol. por vistoria de unidade consumidora de área rural (art. 30)"},
{id: 'CRVistUb', text: "Créd. Prazo Viol. por vistoria de unidade consumidora de área urbana (art. 30)"},
{id: 'CRVrfResfr', text: "Créd. Prazo Viol. de verif. de equip. de resfriamento por ressarc. (art. 206)"},
{id: 'CRVrfRsc', text: "Créd. Prazo Viol. de verif. de equip. por ressarc. de dano elétrico (art. 206)"},
{id: 'DEC', text: "Duração Equivalente de Interrupção por Unidade Consumidora - 3 Min."},
{id: 'Dec1', text: "Duração Equivalente de Interrupção por Unidade Consumidora - 1 Min."},
{id: 'DEC1i', text: "Duração Equivalente de Interrupção por Unid. Cons. Decor.Rede Própria - 1 Min"},
{id: 'Dec1r', text: "Duração Equivalente de Interrupção por Unidade Consumidora (Racion.)- 1 Min."},
{id: 'DEC1x', text: "Duração Equivalente de Interrupção por Unid. Cons. Fat. Externos - 1 Min."},
{id: 'DECi', text: "Duração Equivalente de Interrupção por Unid. Cons. Decor. Rede Própia - 3 Min."},
{id: 'DECINC', text: "DEC de interrup. origem interna ao Sist. de Dist. não progr. e ocor. Dia Crítico"},
{id: 'DECIND', text: "DEC interrup origem interna, não programada e não expurgavel"},
{id: 'DECINE', text: "DEC interrup. origem interna, não progr. e ocor. Sit. Emerg, n ocor critico."},
{id: 'DECINO', text: "DEC interrup. origem interna não progr. Racionamento e ONS, n ocor dia critico."},
{id: 'DECIP', text: "DEC de interrupção de origem interna ao Sist. de Dist. e programada"},
{id: 'DECIPC', text: "DEC interrup. origem inter. ao sist distr, prog. e ocorr. em dia crítico"},
{id: 'Decr', text: "Duração Equivalente de Interrupção por Unidade Consumidora (Racion.)- 3 Min."},
{id: 'DECx', text: "Duração Equivalente de Interrupção por Unid. Cons. Decor. Fat. Externos - 3 Min."},
{id: 'DECXN', text: "DEC de interrupção de origem externa ao Sist. de Dist. e não programada"},
{id: 'DECXNC', text: "DEC interrup. origem ext. ao sist distr, não prog. e ocorr. em dia crítico"},
{id: 'DECXP', text: "DEC de interrupção de origem externa ao Sist. de Dist. e programada"},
{id: 'DECXPC', text: "DEC interrup. origem ext. ao sist distr, prog. e ocorr. em dia crítico"},
{id: 'DIADEBPDO', text: "Dias Debitados - Próprio Doença"},
{id: 'DIADEBPTJ', text: "Dias Debitados - Próprio Trajeto"},
{id: 'DIADEBPTP', text: "Dias Debitados - Próprio Típico"},
{id: 'DIADEBTTP', text: "Dias Debitados - Terceirizado Típico"},
{id: 'DIAPRDPDO', text: "Dias Perdidos - Próprio Doença"},
{id: 'DIAPRDPTJ', text: "Dias Perdidos - Próprio Trajeto"},
{id: 'DIAPRDPTP', text: "Dias Perdidos - Próprio Típico"},
{id: 'DIAPRDTTP', text: "Dias Perdidos - Terceirizado Típico"},
{id: 'DICVLD', text: "Valor apurado do indicador DIC"},
{id: 'DICVLDA', text: "Valor apurado do indicador DIC"},
{id: 'DICVLDT', text: "Valor apurado do indicador DIC"},
{id: 'DMICVLD', text: "Valor apurado do indicador DMIC"},
{id: 'DMICVLDA', text: "Valor apurado do indicador DMIC violado"},
{id: 'DMICVLDT', text: "Valor apurado do indicador DMIC violado"},
{id: 'DRC', text: "Duração Relativa da Transgressão Máxima de Tensão Crítica Mensal"},
{id: 'DRCt', text: "Duração Relativa da Transgressão Máxima de Tensão Crítica"},
{id: 'DRCVLD', text: "Valor apurado do indicador DRC violado"},
{id: 'DRP', text: "Duração Relativa da Transgressão Máxima de Tensão Precária Mensal"},
{id: 'DRPt', text: "Duração Relativa da Transgressão Máxima de Tensão Precária"},
{id: 'DRPVLD', text: "Valor apurado do indicador DRP violado"},
{id: 'ERP', text: "Extensão de rede primária com nível de tensão inferior a 69kV, em km"},
{id: 'ERPT', text: "Extensão de Rede Primária em km"},
{id: 'ERPTRU', text: "Ext de rede de MT que atendem a área rur, redes próp e redes particulares"},
{id: 'ERPTUR', text: "Ext de rede de MT que atendem a área urb, redes próp e redes particulares"},
{id: 'FEC', text: "Freqüência Equivalente de Interrupção por Unidade Consumidora - 3 Min."},
{id: 'Fec1', text: "Freqüencia Equivalente de Interrupção por Unidade Consumidora - 1 Min."},
{id: 'FEC1i', text: "Freqüência Equivalente de Interrupção por Unid. Cons. Decor.Rede Própria - 1 Min"},
{id: 'Fec1r', text: "Freqüência Equivalente de Interrupção por Unidade Consumidora (Racion.)- 1 Min."},
{id: 'FEC1x', text: "Freqüência Equivalente de Interrupção por Unid. Cons. Fat. Externos - 1 Min"},
{id: 'FECi', text: "Freqüência Equivalente de Interrupção por Unid. Cons. Decor.Rede Própria - 3 Min"},
{id: 'FECINC', text: "FEC de interrup. origem interna ao Sist. de Dist. não progr. e ocor. Dia Crítico"},
{id: 'FECIND', text: "FEC interrup origem interna, não programada e não expurgavel"},
{id: 'FECINE', text: "FEC interrup. origem interna, não progr. e ocor. Sit. Emerg, n ocor critico."},
{id: 'FECINO', text: "FEC interrup. origem interna não progr. Racionamento e ONS, n ocor dia critico."},
{id: 'FECIP', text: "FEC de interrupção de origem interna ao Sist. de Dist. e programada"},
{id: 'FECIPC', text: "FEC interrup. origem inter. ao sist distr, prog. e ocorr. em dia crítico"},
{id: 'Fecr', text: "Freqüência Equivalente de Interrupção por Unidade Consumidora (Racion.)- 3 Min."},
{id: 'FECx', text: "Freqüência Equivalente de Interrupção por Unid. Cons. Decor.Fat.Externos - 3 Min"},
{id: 'FECXN', text: "FEC de interrupção de origem externa ao Sist. de Dist. e não programada"},
{id: 'FECXNC', text: "FEC interrup. origem ext. ao sist distr, não prog. e ocorr. em dia crítico"},
{id: 'FECXP', text: "FEC de interrupção de origem externa ao Sist. de Dist. e programada"},
{id: 'FECXPC', text: "FEC interrup. origem ext. ao sist distr, prog. e ocorr. em dia crítico"},
{id: 'FICVLD', text: "Valor apurado do indicador FIC"},
{id: 'FICVLDA', text: "Valor apurado do indicador FIC"},
{id: 'FICVLDT', text: "Valor apurado do indicador FIC"},
{id: 'FQACCAPDO', text: "Taxa de frequência de acidentados com lesão com afastamento - Próprio"},
{id: 'FQACCAPTP', text: "Taxa de frequência de acidentados com lesão com afastamento - Próprio"},
{id: 'FQACCATTP', text: "Taxa de frequência de acidentados com lesão com afastamento - Terceiri"},
{id: 'FQACPDO', text: "Taxa de frequencia de acidentes do trabalho - Próprio Doença"},
{id: 'FQACPTP', text: "Taxa de frequencia de acidentes do trabalho - Próprio Típico"},
{id: 'FQACSAPDO', text: "Taxa de frequência de acidentados com lesão sem afastamento - Próprio"},
{id: 'FQACSAPTP', text: "Taxa de frequência de acidentados com lesão sem afastamento - Próprio"},
{id: 'FQACSATTP', text: "Taxa de frequência de acidentados com lesão sem afastamento - Terceiri"},
{id: 'FQACTTP', text: "Taxa de frequencia de acidentes do trabalho - Terceirizado Típico"},
{id: 'GRVACPDO', text: "Taxa de gravidade de acidentes do trabalho - Próprio Doença"},
{id: 'GRVACPTP', text: "Taxa de gravidade de acidentes do trabalho - Próprio Típico"},
{id: 'GRVACTTP', text: "Taxa de gravidade de acidentes do trabalho - Terceirizado Típico"},
{id: 'HHRISACP', text: "Horas-Homem de exposição ao risco de acidentes - Próprio"},
{id: 'HHRISACT', text: "Horas-Homem de exposição ao risco de acidentes - Terceirizado"},
{id: 'ICC', text: "Índices de Unidades Consumidoras com Tensão Crítica"},
{id: 'ICom1', text: "Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Comercial"},
{id: 'ICom12', text: "Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Comercial"},
{id: 'ICom18', text: "Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Comercial"},
{id: 'ICom21', text: "Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Comercial"},
{id: 'ICom24', text: "Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Comercial"},
{id: 'ICom3', text: "Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Comercial"},
{id: 'ICom6', text: "Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Comercial"},
{id: 'IComCrt', text: "Quant. de unid. da classe Comercial susp. inadimplência no mês de ref."},
{id: 'ICProp1', text: "Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Consumo Próp."},
{id: 'ICProp12', text: "Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Consumo Próp."},
{id: 'ICProp18', text: "Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Consumo Próp."},
{id: 'ICProp21', text: "Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Consumo Próp."},
{id: 'ICProp24', text: "Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Consumo Próp."},
{id: 'ICProp3', text: "Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Consumo Próp."},
{id: 'ICProp6', text: "Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Consumo Próp."},
{id: 'ICPropCrt', text: "Quant. de unid. da classe Consumo Próp. susp. inadimplência no mês de ref."},
{id: 'IInd1', text: "Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Industrial"},
{id: 'IInd12', text: "Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Industrial"},
{id: 'IInd18', text: "Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Industrial"},
{id: 'IInd21', text: "Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Industrial"},
{id: 'IInd24', text: "Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Industrial"},
{id: 'IInd3', text: "Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Industrial"},
{id: 'IInd6', text: "Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Industrial"},
{id: 'IIndCrt', text: "Quant. de unid. da classe Industrial susp. inadimplência no mês de ref."},
{id: 'IIPub1', text: "Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Iluminação Púb."},
{id: 'IIPub12', text: "Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Iluminação Púb."},
{id: 'IIPub18', text: "Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Iluminação Púb."},
{id: 'IIPub21', text: "Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Iluminação Púb."},
{id: 'IIPub24', text: "Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Iluminação Púb."},
{id: 'IIPub3', text: "Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Iluminação Púb."},
{id: 'IIPub6', text: "Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Iluminação Púb."},
{id: 'IIPubCrt', text: "Quant. de unid. da classe Iluminação Púb. susp. inadimplência no mês de ref."},
{id: 'IPPub1', text: "Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Poder Púb."},
{id: 'IPPub12', text: "Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Poder Púb."},
{id: 'IPPub18', text: "Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Poder Púb."},
{id: 'IPPub21', text: "Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Poder Púb."},
{id: 'IPPub24', text: "Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Poder Púb."},
{id: 'IPPub3', text: "Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Poder Púb."},
{id: 'IPPub6', text: "Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Poder Púb."},
{id: 'IPPubCrt', text: "Quant. de unid. da classe Poder Púb. susp. inadimplência no mês de ref."},
{id: 'IResBR1', text: "Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Resid. Baixa R."},
{id: 'IResBR12', text: "Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Resid. Baixa R."},
{id: 'IResBR18', text: "Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Resid. Baixa R."},
{id: 'IResBR21', text: "Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Resid. Baixa R."},
{id: 'IResBR24', text: "Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Resid. Baixa R."},
{id: 'IResBR3', text: "Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Resid. Baixa R."},
{id: 'IResBR6', text: "Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Resid. Baixa R."},
{id: 'IResBRCrt', text: "Quant. de unid. da classe Resid. Baixa R. susp. inadimplência no mês de ref."},
{id: 'IResTot1', text: "Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Resid. Total"},
{id: 'IRestot12', text: "Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Resid. Total"},
{id: 'IRestot18', text: "Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Resid. Total"},
{id: 'IRestot21', text: "Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Resid. Total"},
{id: 'IRestot24', text: "Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Resid. Total"},
{id: 'IRestot3', text: "Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Resid. Total"},
{id: 'IRestot6', text: "Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Resid. Total"},
{id: 'IResTotCrt', text: "Quant. de unid. da classe Resid. Total susp. inadimplência no mês de ref."},
{id: 'IRur1', text: "Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Rural"},
{id: 'IRur12', text: "Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Rural"},
{id: 'IRur18', text: "Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Rural"},
{id: 'IRur21', text: "Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Rural"},
{id: 'IRur24', text: "Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Rural"},
{id: 'IRur3', text: "Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Rural"},
{id: 'IRur6', text: "Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Rural"},
{id: 'IRurCrt', text: "Quant. de unid. da classe Rural susp. inadimplência no mês de ref."},
{id: 'ISerPub1', text: "Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Serviço Púb."},
{id: 'ISerPub12', text: "Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Serviço Púb."},
{id: 'ISerPub18', text: "Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Serviço Púb."},
{id: 'ISerPub21', text: "Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Serviço Púb."},
{id: 'ISerPub24', text: "Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Serviço Púb."},
{id: 'ISerPub3', text: "Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Serviço Púb."},
{id: 'ISerPub6', text: "Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Serviço Púb."},
{id: 'ISerPubCrt', text: "Quant. de unid. da classe Serviço Púb. susp. inadimplência no mês de ref."},
{id: 'ITot1', text: "Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. todos os consumidores"},
{id: 'ITot12', text: "Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. todos os consumidores"},
{id: 'ITot18', text: "Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. todos os consumidores"},
{id: 'ITot21', text: "Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. todos os consumidores"},
{id: 'ITot24', text: "Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. todos os consumidores"},
{id: 'ITot3', text: "Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. todos os consumidores"},
{id: 'ITot6', text: "Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. todos os consumidores"},
{id: 'ITotCrt', text: "Quant. total de unid. consumidoras susp. inadimplência no mês de referência"},
{id: 'k3', text: "Valor do encargo de uso do sistema de distribuição"},
{id: 'LOCUC', text: "Localização da Unidade Consumidora"},
{id: 'LOCUCA', text: "Localização da Unidade Consumidora"},
{id: 'LOCUCT', text: "Localização da Unidade Consumidora"},
{id: 'NACCAPDO', text: "Número de acidentados com lesão e com afastamento - Próprio Doença"},
{id: 'NACCAPTJ', text: "Número de acidentados com lesão e com afastamento - Próprio Trajeto"},
{id: 'NACCAPTP', text: "Número de acidentados com lesão e com afastamento - Próprio Típico"},
{id: 'NACCATDO', text: "Número de acidentados com lesão e com afastamento - Terceirizado Doença"},
{id: 'NACCATTJ', text: "Número de acidentados com lesão e com afastamento - Terceirizado Trajet"},
{id: 'NACCATTP', text: "Número de acidentados com lesão e com afastamento - Terceirizado Típico"},
{id: 'NACPDO', text: "Número de acidentes do trabalho - Próprio Doença"},
{id: 'NACPTJ', text: "Número de acidentes do trabalho - Próprio Trajeto"},
{id: 'NACPTP', text: "Número de acidentes do trabalho - Próprio Típico"},
{id: 'NACSAPDO', text: "Número de acidentados com lesão e sem afastamento - Próprio Doença"},
{id: 'NACSAPTJ', text: "Número de acidentados com lesão e sem afastamento - Próprio Trajeto"},
{id: 'NACSAPTP', text: "Número de acidentados com lesão e sem afastamento - Próprio Típico"},
{id: 'NACSATDO', text: "Número de acidentados com lesão e sem afastamento - Terceirizado Doença"},
{id: 'NACSATTJ', text: "Número de acidentados com lesão e sem afastamento - Terceirizado Trajet"},
{id: 'NACSATTP', text: "Número de acidentados com lesão e sem afastamento - Terceirizado Típico"},
{id: 'NACTDO', text: "Número de acidentes do trabalho - Terceirizado Doença"},
{id: 'NACTER', text: "Número de acidentes com terceiros envolvendo a rede elétrica e demais instalaçõe"},
{id: 'NACTERANT', text: "Nº acid terc rede e demais instal - Antena de TV"},
{id: 'NACTERCFE', text: "Nº acid terc rede e demais instal - Cabo energizado no solo ou falha de equip"},
{id: 'NACTERCHO', text: "Nº acid terc rede e demais instal - Choque elétrico por contato"},
{id: 'NACTERCLN', text: "Nº acid terc rede e demais instal - Ligações clandestinas"},
{id: 'NACTERCMP', text: "Nº acid terc rede e demais instal - Construção e manutenção predial"},
{id: 'NACTERFUR', text: "Nº acid terc rede e demais instal - Furto de cabos e/ou outros equipamentos"},
{id: 'NACTERGUI', text: "Nº acid terc rede e demais instal - Operação de guindaste"},
{id: 'NACTEROUT', text: "Nº acid terc rede e demais instal - Outros."},
{id: 'NACTERPIP', text: "Nº acid terc rede e demais instal - Pipa"},
{id: 'NACTERPOD', text: "Nº acid terc rede e demais instal - Poda de árvore"},
{id: 'NACTERPST', text: "Nº acid terc rede e demais instal - Abalroamento de poste e/ou demais instal."},
{id: 'NACTERTVC', text: "Nº acid terc rede e demais instal - Serviços de TV a cabo e telefonia"},
{id: 'NACTTJ', text: "Número de acidentes do trabalho - Terceirizado Trajeto"},
{id: 'NACTTP', text: "Número de acidentes do trabalho - Terceirizado Típico"},
{id: 'NDIACRI', text: "Número de dias críticos verificados no ano"},
{id: 'NEMPRP', text: "Números de Empregados - Próprio"},
{id: 'NEMPRT', text: "Números de Empregados - Terceirizado"},
{id: 'Nie', text: "Número de Ocorreências Emergenciais com Interrupções"},
{id: 'NMOFUPR', text: "Número de mortes de decorrentes de acidentes do trabalho (funcionários próprios)"},
{id: 'NMOFUTE', text: "Número de mortes decorrentes de acidentes do trabalho (funcionários terceirizado"},
{id: 'NMOPDO', text: "Número de mortes de decorrentes de acidentes do trabalho - Próprio Doença"},
{id: 'NMOPTJ', text: "Número de mortes de decorrentes de acidentes do trabalho - Próprio Trajet"},
{id: 'NMOPTP', text: "Número de mortes de decorrentes de acidentes do trabalho - Próprio Típico"},
{id: 'NMOTDO', text: "Número de mortes de decorrentes de acidentes do trabalho - Terceirizado Doença"},
{id: 'NMOTER', text: "Número de mortes decorrentes de acidentes com terceiros envolvendo a rede elétri"},
{id: 'NMOTERANT', text: "Nº mortes terc rede e demais instal - Antena de TV"},
{id: 'NMOTERCFE', text: "Nº mortes terc rede e demais instal - Cabo energizado no solo ou falha de equip"},
{id: 'NMOTERCHO', text: "Nº mortes terc rede e demais instal - Choque elétrico por contato"},
{id: 'NMOTERCLN', text: "Nº mortes terc rede e demais instal - Ligações clandestinas"},
{id: 'NMOTERCMP', text: "Nº mortes terc rede e demais instal - Construção e manutenção predial"},
{id: 'NMOTERFUR', text: "Nº mortes terc rede e demais instal - Furto de cabos e/ou outros equip"},
{id: 'NMOTERGUI', text: "Nº mortes terc rede e demais instal - Operação de guindaste"},
{id: 'NMOTEROUT', text: "Nº mortes terc rede e demais instal - Outros."},
{id: 'NMOTERPIP', text: "Nº mortes terc rede e demais instal - Pipa"},
{id: 'NMOTERPOD', text: "Nº mortes terc rede e demais instal - Poda de árvore"},
{id: 'NMOTERPST', text: "Nº mortes terc rede e demais instal - Abalroamento de poste e/ou demais inst"},
{id: 'NMOTERTVC', text: "Nº mortes terc rede e demais instal - Serviços de TV a cabo e telef"},
{id: 'NMOTTJ', text: "Número de mortes de decorrentes de acidentes do trabalho - Terceirizado Trajeto"},
{id: 'NMOTTP', text: "Número de mortes de decorrentes de acidentes do trabalho - Terceirizado Típico"},
{id: 'NUCTCO', text: "Total de unidades consumidoras comercial MT e BT"},
{id: 'NUCTIN', text: "Total de unidades consumidoras industrial MT e BT"},
{id: 'NUCTOU', text: "Total de unidades consumidoras de outras classes  MT e BT"},
{id: 'NUCTRE', text: "Total de unidades consumidoras residencial MT e BT"},
{id: 'NUCTRU', text: "Total de unidades consumidoras rural MT e BT"},
{id: 'NumCon', text: "Número de Consumidores do Conjunto no Período"},
{id: 'NumConsAgt', text: "Número de Consumidores do Distribuidor no Período"},
{id: 'NumOcorr', text: "Número de Ocorrencias Emergenciais no Conjunto no Período"},
{id: 'PGUCAT', text: "Valor pago a UCs AT por violacao dos limites de continuidade no mes"},
{id: 'PGUCATA', text: "Valor pago a UCs AT por violacao dos limites de cont no ano"},
{id: 'PGUCATDC', text: "Valor pago as UCs AT por violacao dos limites de DICRI"},
{id: 'PGUCATT', text: "Valor pago a UCs AT por violacao dos limites de cont no trimestre"},
{id: 'PGUCBTNU', text: "Valor pago a UCs BT não urbanas por violacao dos limites de cont no mes"},
{id: 'PGUCBTNUA', text: "Valor pago a UCs BT não urbanas por violacao dos limites de cont no ano"},
{id: 'PGUCBTNUDC', text: "Valor pago as UCs BT não urbanas por violacao dos limites de DICRI"},
{id: 'PGUCBTNUT', text: "Valor pago a UCs BT não urbanas por violacao dos limites de cont no trimestre"},
{id: 'PGUCBTU', text: "Valor pago a UCs BT urbanas por violacao dos limites de continuidade no mes"},
{id: 'PGUCBTUA', text: "Valor pago a UCs BT urbanas por violacao dos limites de cont no ano"},
{id: 'PGUCBTUDC', text: "Valor pago as UCs BT urbanas por violacao dos limites de DICRI"},
{id: 'PGUCBTUT', text: "Valor pago a UCs BT urbanas por violacao dos limites de cont no trimestre"},
{id: 'PGUCMTNU', text: "Valor pago a UCs MT não urbanas por violacao dos limites de cont no mes"},
{id: 'PGUCMTNUA', text: "Valor pago a UCs MT não urbanas por violacao dos limites de cont no ano"},
{id: 'PGUCMTNUDC', text: "Valor pago as UCs MT não urbanas por violacao dos limites de DICRI"},
{id: 'PGUCMTNUT', text: "Valor pago a UCs MT não urbanas por violacao dos limites de cont no trimestre"},
{id: 'PGUCMTU', text: "Valor pago a UCs MT urbanas por violacao dos limites de continuidade no mes"},
{id: 'PGUCMTUA', text: "Valor pago a UCs MT urbanas por violacao dos limites de cont no ano"},
{id: 'PGUCMTUDC', text: "Valor pago as UCs MT urbanas por violacao dos limites de DICRI"},
{id: 'PGUCMTUT', text: "Valor pago a UCs MT urbanas por violacao dos limites de cont no trimestre"},
{id: 'PGUCTRP', text: "Valor pago a UCs por violacao dos limites de tensao em regime permanente"},
{id: 'PGUCTRPA', text: "Valor pago a UCs por violação limites de tensão em regime perm–med.amostral"},
{id: 'PGUCTRPE', text: "Valor pago a UCs por violação limites de tensão em regime perm–med.eventual"},
{id: 'PGUCTRPP', text: "Valor pago a UCs por violação limites de tensão em regime perm–med.amostral"},
{id: 'PGUGAT', text: "Valor pago a UGs AT por violacao dos limites de continuidade no mes"},
{id: 'PGUGATA', text: "Valor pago a UGs AT por violacao dos limites de cont no ano"},
{id: 'PGUGATDC', text: "Valor pago as UGs AT por violacao dos limites de DICRI"},
{id: 'PGUGATT', text: "Valor pago a UGs AT por violacao dos limites de cont no trimestre"},
{id: 'PGUGBTNU', text: "Valor pago a UGs BT não urbanas por violacao dos limites de cont no mes"},
{id: 'PGUGBTNUA', text: "Valor pago a UGs BT não urbanas por violacao dos limites de cont no ano"},
{id: 'PGUGBTNUDC', text: "Valor pago as UGs BT não urbanas por violacao dos limites de DICRI"},
{id: 'PGUGBTNUT', text: "Valor pago a UGs BT não urbanas por violacao dos limites de cont no trimestre"},
{id: 'PGUGBTU', text: "Valor pago a UGs BT urbanas por violacao dos limites de continuidade no mes"},
{id: 'PGUGBTUA', text: "Valor pago a UGs BT urbanas por violacao dos limites de cont no ano"},
{id: 'PGUGBTUDC', text: "Valor pago as UGs BT urbanas por violacao dos limites de DICRI"},
{id: 'PGUGBTUT', text: "Valor pago a UGs BT urbanas por violacao dos limites de cont no trimestre"},
{id: 'PGUGMTNU', text: "Valor pago a UGs MT não urbanas por violacao dos limites de cont no mes"},
{id: 'PGUGMTNUA', text: "Valor pago a UGs MT não urbanas por violacao dos limites de cont no ano"},
{id: 'PGUGMTNUDC', text: "Valor pago as UGs MT não urbanas por violacao dos limites de DICRI"},
{id: 'PGUGMTNUT', text: "Valor pago a UGs MT não urbanas por violacao dos limites de cont no trimestre"},
{id: 'PGUGMTU', text: "Valor pago a UGs MT urbanas por violacao dos limites de continuidade no mes"},
{id: 'PGUGMTUA', text: "Valor pago a UGs MT urbanas por violacao dos limites de cont no ano"},
{id: 'PGUGMTUDC', text: "Valor pago as UGs MT urbanas por violacao dos limites de DICRI"},
{id: 'PGUGMTUT', text: "Valor pago a UGs MT urbanas por violacao dos limites de cont no trimestre"},
{id: 'PMAfedMed', text: "Prazo Médio de solicitações de aferição dos medidores (art. 137)"},
{id: 'PMAnProj', text: "Prazo Médio de informação do resultado da análise do projeto (art. 27-B)"},
{id: 'PMCmsnObra', text: "Prazo médio de Comissionamento das obras. (art. 37)"},
{id: 'PMEstProj', text: "Prazo Médio de estudos, orçamentos e projetos por obras (art. 32)"},
{id: 'PMInform', text: "Prazo Médio de informação da relação dos atendimentos (art. 199)"},
{id: 'PMLigA', text: "Prazo Médio de ligação de unidade consumidora do grupo A (art. 31)"},
{id: 'PMLigBRr', text: "Prazo Médio de ligação de consumidor do grupo B em área rural (art. 31)"},
{id: 'PMLigBUb', text: "Prazo Médio de ligação de consumidor do grupo B em área urbana (art. 31)"},
{id: 'PMNvCmsn', text: "Prazo médio de Novo comissionamento quando de reprovação. (art. 37)"},
{id: 'PMObGerais', text: "Prazo médio de Conclusão de obra não abrang. nos inc. I e II do art. 34."},
{id: 'PMObra', text: "Prazo Médio de Início das Obras (art. 34)"},
{id: 'PMObraPrim', text: "Prazo médio de Conclusão das obras de até 1 km na rede  prim. (art. 34)"},
{id: 'PMObraSec', text: "Prazo médio de Conclusão das obras na rede tensão sec. (art. 34)"},
{id: 'PMPgtoRsc', text: "Prazo Médio de ressarc. por meio do pgto, conserto ou subst. (art. 208)"},
{id: 'PMRclCobr', text: "Prazo Médio de reclamação de cobrança ou devol. de diferenças (art. 133)"},
{id: 'PMRclDano', text: "Prazo Médio de solução ref. à danos não elétricos reclamados (art. 197)"},
{id: 'PMRclVisTc', text: "Prazo Médio de solução de reclamação com visita técnica (art. 197)"},
{id: 'PMReanProj', text: "Prazo Médio de reanálise do projeto por falta de informação (art. 27-B)"},
{id: 'PMReligIdv', text: "Prazo Médio de religação por suspensão indevida do fornec. (art. 176)"},
{id: 'PMRelNorRr', text: "Prazo Médio de religação em área rural (art. 176)"},
{id: 'PMRelNorUb', text: "Prazo Médio de religação em área urbana (art. 176)"},
{id: 'PMRelUrgRr', text: "Prazo Médio de religação de emergência em área rural (art. 176)"},
{id: 'PMRelUrgUb', text: "Prazo Médio de religação de emergência em área urbana (art. 176)"},
{id: 'PMResulRsc', text: "Prazo Médio de resultado da solicitação de ressarcimento (art. 207)"},
{id: 'PMSubstMed', text: "Prazo Médio de substituição do medidor com defeito (art. 115)"},
{id: 'PMVistRr', text: "Prazo Médio de vistoria de unidade consumidora de área rural (art. 30)"},
{id: 'PMVistUb', text: "Prazo médio de vistoria de unidade consumidora de área urbana (art. 30)"},
{id: 'PMVrfResfr', text: "Prazo Médio de verif. de equip. de resfriamento por ressarc. (art. 206)"},
{id: 'PMVrfRsc', text: "Prazo Médio de verif. de equip. por ressarc. de dano elétrico (art. 206)"},
{id: 'Pnie', text: "Percentual do Número de Ocorreências Emergenciais com Interrupções"},
{id: 'PNIT', text: "Potência instalada de transformadores de distribuição, em kVA, de todos os"},
{id: 'PNITT', text: "Potencia Instalada de transformadores de distribuição em kVA"},
{id: 'QSAfedMed', text: "Quantidade de solicitações de aferição dos medidores (art. 137)"},
{id: 'QSAnProj', text: "Quantidade de informação do resultado da análise do projeto (art. 27-B)"},
{id: 'QSCmsnObra', text: "Quantidade de Comissionamento das obras. (art. 37)"},
{id: 'QSEstProj', text: "Quantidade de estudos, orçamentos e projetos por obras (art. 32)"},
{id: 'QSInform', text: "Quantidade de informação da relação dos atendimentos (art. 199)"},
{id: 'QSLigA', text: "Quantidade de ligação de unidade consumidora do grupo A (art. 31)"},
{id: 'QSLigBRr', text: "Quantidade de ligação de consumidor do grupo B em área rural (art. 31)"},
{id: 'QSLigBUb', text: "Quantidade de ligação de consumidor do grupo B em área urbana (art. 31)"},
{id: 'QSNvCmsn', text: "Quantidade de Novo comissionamento quando de reprovação. (art. 37)"},
{id: 'QSObGerais', text: "Quantidade de Conclusão de obra não abrang. nos inc. I e II do art. 34."},
{id: 'QSObra', text: "Quantidade de Início das Obras (art. 34)"},
{id: 'QSObraPrim', text: "Quantidade de Conclusão das obras de até 1 km na rede prim. (art. 34)"},
{id: 'QSObraSec', text: "Quantidade de Conclusão das obras na rede tensão sec. (art. 34)"},
{id: 'QSPgtoRsc', text: "Quantidade de ressarc. por meio do pgto, conserto ou subst. (art. 208)"},
{id: 'QSRclCobr', text: "Quantidade de reclamação de cobrança ou devol. de diferenças (art. 133)"},
{id: 'QSRclDano', text: "Quantidade de solução ref. à danos não elétricos reclamados (art. 197)"},
{id: 'QSRclVisTc', text: "Quantidade de solução de reclamação com visita técnica (art. 197)"},
{id: 'QSReanProj', text: "Quantidade de reanálise do projeto por falta de informação (art. 27-B)"},
{id: 'QSReligIdv', text: "Quantidade de religação por suspensão indevida do fornec. (art. 176)"},
{id: 'QSRelNorRr', text: "Quantidade de religação em área rural (art. 176)"},
{id: 'QSRelNorUb', text: "Quantidade de religação em área urbana (art. 176)"},
{id: 'QSRelUrgRr', text: "Quantidade de religação de emergência em área rural (art. 176)"},
{id: 'QSRelUrgUb', text: "Quantidade de religação de emergência em área urbana (art. 176)"},
{id: 'QSResulRsc', text: "Quantidade de resultado da solicitação de ressarcimento (art. 207)"},
{id: 'QSSubstMed', text: "Quantidade de substituição do medidor com defeito (art. 115)"},
{id: 'QSVistRr', text: "Quantidade de vistoria de unidade consumidora de área rural (art. 30)"},
{id: 'QSVistUb', text: "Quantidade de vistoria de unidade consumidora de área urbana (art. 30)"},
{id: 'QSVrfResfr', text: "Quantidade de verif. de equip. de resfriamento por ressarc. (art. 206)"},
{id: 'QSVrfRsc', text: "Quantidade de verif. de equip. por ressarc. de dano elétrico (art. 206)"},
{id: 'QTUCAT', text: "Qtde de UCs AT compensadas por violacao dos limites de continuidade no mes"},
{id: 'QTUCATA', text: "Qtde de UCs AT compens por violacao dos limites de cont no ano"},
{id: 'QTUCATDC', text: "Qtde de UCs AT comp por violacao dos limites de DICRI"},
{id: 'QTUCATT', text: "Qtde de UCs AT compens por violacao dos limites de cont no trimestre"},
{id: 'QTUCBTNU', text: "Qtde de UCs BT não urbanas comp por violacao dos limites de cont no mes"},
{id: 'QTUCBTNUA', text: "Qtde de UCs BT não urbanas comp por violacao dos limites de cont no ano"},
{id: 'QTUCBTNUDC', text: "Qtde de UCs BT não urbanas comp por violacao dos limites de DICRI"},
{id: 'QTUCBTNUT', text: "Qtde de UCs BT não urbanas comp por violacao dos limites de cont no trimestre"},
{id: 'QTUCBTU', text: "Qtde de UCs BT urbanas compensadas por violacao dos limites de cont no mes"},
{id: 'QTUCBTUA', text: "Qtde de UCs BT urbanas compens por violacao dos limites de cont no ano"},
{id: 'QTUCBTUDC', text: "Qtde de UCs BT urbanas comp por violacao dos limites de DICRI"},
{id: 'QTUCBTUT', text: "Qtde de UCs BT urbanas compens por violacao dos limites de cont no trimestre"},
{id: 'QTUCMTNU', text: "Qtde de UCs MT não urbanas comp por violacao dos limites de cont no mes"},
{id: 'QTUCMTNUA', text: "Qtde de UCs MT não urbanas comp por violacao dos limites de cont no ano"},
{id: 'QTUCMTNUDC', text: "Qtde de UCs MT não urbanas comp por violacao dos limites de DICRI"},
{id: 'QTUCMTNUT', text: "Qtde de UCs MT não urbanas comp por violacao dos limites de cont no trimestre"},
{id: 'QTUCMTU', text: "Qtde de UCs MT urbanas compensadas por violacao dos limites de cont no mes"},
{id: 'QTUCMTUA', text: "Qtde de UCs MT urbanas compens por violacao dos limites de cont no ano"},
{id: 'QTUCMTUDC', text: "Qtde de UCs MT urbanas comp por violacao dos limites de DICRI"},
{id: 'QTUCMTUT', text: "Qtde de UCs MT urbanas compens por violacao dos limites de cont no trimestre"},
{id: 'QTUCTRP', text: "Qtde de UCs comp por violacao dos limites de tensao em regime permanente"},
{id: 'QTUCTRPA', text: "Qtde de UC compens.-violação limites de tensão em regime perm–med.amostral"},
{id: 'QTUCTRPE', text: "Qtde de UC compens.-violação limites de tensão em regime perm–med.eventual"},
{id: 'QTUCTRPP', text: "Qtde de UC compens.-violação limites de tensão em regime perm–med.perman."},
{id: 'QTUGAT', text: "Qtde de UGs AT compensadas por violacao dos limites de continuidade no mes"},
{id: 'QTUGATA', text: "Qtde de UGs AT compens por violacao dos limites de cont no ano"},
{id: 'QTUGATDC', text: "Qtde de UGs AT comp por violacao dos limites de DICRI"},
{id: 'QTUGATT', text: "Qtde de UGs AT compens por violacao dos limites de cont no trimestre"},
{id: 'QTUGBTNU', text: "Qtde de UGs BT não urbanas comp por violacao dos limites de cont no mes"},
{id: 'QTUGBTNUA', text: "Qtde de UGs BT não urbanas comp por violacao dos limites de cont no ano"},
{id: 'QTUGBTNUDC', text: "Qtde de UGs BT não urbanas comp por violacao dos limites de DICRI"},
{id: 'QTUGBTNUT', text: "Qtde de UGs BT não urbanas comp por violacao dos limites de cont no trimestre"},
{id: 'QTUGBTU', text: "Qtde de UGs BT urbanas compensadas por violacao dos limites de cont no mes"},
{id: 'QTUGBTUA', text: "Qtde de UGs BT urbanas compens por violacao dos limites de cont no ano"},
{id: 'QTUGBTUDC', text: "Qtde de UGs BT urbanas comp por violacao dos limites de DICRI"},
{id: 'QTUGBTUT', text: "Qtde de UGs BT urbanas compens por violacao dos limites de cont no trimestre"},
{id: 'QTUGMTNU', text: "Qtde de UGs MT não urbanas comp por violacao dos limites de cont no mes"},
{id: 'QTUGMTNUA', text: "Qtde de UGs MT não urbanas comp por violacao dos limites de cont no ano"},
{id: 'QTUGMTNUDC', text: "Qtde de UGs MT não urbanas comp por violacao dos limites de DICRI"},
{id: 'QTUGMTNUT', text: "Qtde de UGs MT não urbanas comp por violacao dos limites de cont no trimestre"},
{id: 'QTUGMTU', text: "Qtde de UGs MT urbanas compensadas por violacao dos limites de cont no mes"},
{id: 'QTUGMTUA', text: "Qtde de UGs MT urbanas compens por violacao dos limites de cont no ano"},
{id: 'QTUGMTUDC', text: "Qtde de UGs MT urbanas comp por violacao dos limites de DICRI"},
{id: 'QTUGMTUT', text: "Qtde de UGs MT urbanas compens por violacao dos limites de cont no trimestre"},
{id: 'QVAfedMed', text: "Quant. Prazos Viol. de solicitações de aferição dos medidores (art. 137)"},
{id: 'QVAnProj', text: "Quant. Prazos Viol. de informação do resultado da análise do projeto (art. 27-B)"},
{id: 'QVCmsnObra', text: "Quant. Prazos Viol. de Comissionamento das obras. (art. 37)"},
{id: 'QVEstProj', text: "Quant. Prazos Viol. de estudos, orçamentos e projetos por obras (art. 32)"},
{id: 'QVInform', text: "Quant. Prazos Viol. de informação da relação dos atendimentos (art. 199)"},
{id: 'QVLigA', text: "Quant. Prazos Viol. de ligação de unidade consumidora do grupo A (art. 31)"},
{id: 'QVLigBRr', text: "Quant. Prazos Viol. de ligação de consumidor do grupo B em área rural (art. 31)"},
{id: 'QVLigBUb', text: "Quant. Prazos Viol. de ligação de consumidor do grupo B em área urbana (art. 31)"},
{id: 'QVNvCmsn', text: "Quant. Prazos Viol. de Novo comissionamento quando de reprovação. (art. 37)"},
{id: 'QVObGerais', text: "Quant. Prazos Viol. de Conclusão de obra não abrang. nos inc. I e II do art. 34."},
{id: 'QVObra', text: "Quant. Prazos Viol. de Início das Obras (art. 34)"},
{id: 'QVObraPrim', text: "Quant. Prazos Viol. de Conclusão das obras de até 1 km na rede prim. (art. 34)"},
{id: 'QVObraSec', text: "Quant. Prazos Viol. de Conclusão das obras na rede tensão sec. (art. 34)"},
{id: 'QVPgtoRsc', text: "Quant. Prazos Viol. de ressarc. por meio do pgto, conserto ou subst. (art. 208)"},
{id: 'QVRclCobr', text: "Quant. Prazos Viol. de reclamação de cobrança ou devol. de diferenças (art. 133)"},
{id: 'QVRclDano', text: "Quant. Prazos Viol. de solução ref. à danos não elétricos reclamados (art. 197)"},
{id: 'QVRclVisTc', text: "Quant. Prazos Viol. de solução de reclamação com visita técnica (art. 197)"},
{id: 'QVReanProj', text: "Quant. Prazos Viol. de reanálise do projeto por falta de informação (art. 27-B)"},
{id: 'QVReligIdv', text: "Quant. Prazos Viol. de religação por suspensão indevida do fornec. (art. 176)"},
{id: 'QVRelNorRr', text: "Quant. Prazos Viol. de religação em área rural (art. 176)"},
{id: 'QVRelNorUb', text: "Quant. Prazos Viol. de religação em área urbana (art. 176)"},
{id: 'QVRelUrgRr', text: "Quant. Prazos Viol. de religação de emergência em área rural (art. 176)"},
{id: 'QVRelUrgUb', text: "Quant. Prazos Viol. de religação de emergência em área urbana (art. 176)"},
{id: 'QVResulRsc', text: "Quant. Prazos Viol. de resultado da solicitação de ressarcimento (art. 207)"},
{id: 'QVSubstMed', text: "Quant. Prazos Viol. de substituição do medidor com defeito (art. 115)"},
{id: 'QVVistRr', text: "Quant. Prazos Viol. vistoria de unidade consumidora de área rural (art. 30)"},
{id: 'QVVistUb', text: "Quant. Prazos Viol. de vistoria de unidade consumidora de área urbana (art. 30)"},
{id: 'QVVrfResfr', text: "Quant. Prazos Viol. de verif. de equip. de resfriamento por ressarc. (art. 206)"},
{id: 'QVVrfRsc', text: "Quant. Prazos Viol. de verif. de equip. por ressarc. de dano elétrico (art. 206)"},
{id: 'TI1', text: "Tensão Interna"},
{id: 'TMD', text: "Tempo Médio de Deslocamento"},
{id: 'TME', text: "Tempo Médio de Execução"},
{id: 'TMM', text: "Tempo Médio de Mobilização"},
{id: 'TMP', text: "Tempo Médio de Preparação"},
{id: 'TNS', text: "Tensão"},
{id: 'TNSA', text: "Tensão"},
{id: 'TNST', text: "Tensão"},
{id: 'TSC', text: "Tipo de sistema do conjunto, 1: Sistema Interligado"},
{id: 'TSCT', text: "Tipo de sistema do conjunto. 1: Interligado, 2: Isolado"},
{id: 'TXFQAC', text: "Taxa de frequencia de acidentes do trabalho"},
{id: 'TXGRAC', text: "Taxa de gravidade de acidentes do trabalho"},
{id: 'VLCLACRI', text: "Valor utilizado no ano para identificar se um dia pode ser classificado critico"},
];

$("#indicador_qualidade").select2({
    data: indicadores
})